/**
 * Build lib/client.js and lib/index.js from src/.
 *
 * The browser bundle is hand-wrapped rather than bundled: the client module
 * system is a lazy CJS registry (`window.__ModuleLoader__.load({id, factory})`),
 * React is an externals lookup, and the game has no other dependency — so a
 * text transform is enough, and the shipped code stays byte-identical to the
 * source that the test suite exercises.
 *
 *   node build.mjs
 */
import fs from 'node:fs'
import path from 'node:path'

const here = path.dirname(new URL(import.meta.url).pathname)
const pkg = JSON.parse(fs.readFileSync(path.join(here, 'package.json'), 'utf8'))
const read = (p) => fs.readFileSync(path.join(here, p), 'utf8')

const body = read('src/game.js')
const host = read('src/host.js')
const banner = (what) => `/* ${pkg.name} ${what} v${pkg.version} — generated by build.mjs; edit src/ instead. */\n`

// The body is emitted verbatim (no re-indentation) so stack traces line up with
// src/game.js. LIFE_DURABLE is what switches the preference store on.
const client =
  banner('client bundle') +
  'window.__ModuleLoader__.load({\n' +
  `  id: ${JSON.stringify(pkg.name)},\n` +
  '  factory: (require) => {\n' +
  '    const React = require("react")\n' +
  '    const LIFE_DURABLE = true\n' +
  '    /** The dynamic runner hands the body a styles builtin; here it is ours. */\n' +
  '    const styles = {\n' +
  '      insert(css) {\n' +
  '        const tag = document.createElement("style")\n' +
  `        tag.dataset.plugin = ${JSON.stringify(pkg.name)}\n` +
  '        tag.textContent = css\n' +
  '        document.head.appendChild(tag)\n' +
  '        return () => { if (tag.parentNode) tag.parentNode.removeChild(tag) }\n' +
  '      },\n' +
  '    }\n' +
  '    return (function () {\n' +
  body +
  '\n    })()\n' +
  '  },\n' +
  '})\n'

fs.mkdirSync(path.join(here, 'lib'), { recursive: true })
fs.writeFileSync(path.join(here, 'lib/client.js'), client)
fs.writeFileSync(path.join(here, 'lib/index.js'), banner('host half') + host)
console.log('built lib/client.js (' + client.length + ' bytes) and lib/index.js (' + host.length + ' bytes)')
